/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasbeehRouteImport } from './routes/tasbeeh'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AzkarIndexRouteImport } from './routes/azkar.index'
import { Route as AzkarCategoryRouteImport } from './routes/azkar.$category'

const TasbeehRoute = TasbeehRouteImport.update({
  id: '/tasbeeh',
  path: '/tasbeeh',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarIndexRoute = AzkarIndexRouteImport.update({
  id: '/azkar/',
  path: '/azkar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AzkarCategoryRoute = AzkarCategoryRouteImport.update({
  id: '/azkar/$category',
  path: '/azkar/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/tasbeeh': typeof TasbeehRoute
  '/azkar/$category': typeof AzkarCategoryRoute
  '/azkar/': typeof AzkarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/tasbeeh': typeof TasbeehRoute
  '/azkar/$category': typeof AzkarCategoryRoute
  '/azkar': typeof AzkarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/tasbeeh': typeof TasbeehRoute
  '/azkar/$category': typeof AzkarCategoryRoute
  '/azkar/': typeof AzkarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/prayer-times'
    | '/qibla'
    | '/search'
    | '/settings'
    | '/stats'
    | '/tasbeeh'
    | '/azkar/$category'
    | '/azkar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/prayer-times'
    | '/qibla'
    | '/search'
    | '/settings'
    | '/stats'
    | '/tasbeeh'
    | '/azkar/$category'
    | '/azkar'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/prayer-times'
    | '/qibla'
    | '/search'
    | '/settings'
    | '/stats'
    | '/tasbeeh'
    | '/azkar/$category'
    | '/azkar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  QiblaRoute: typeof QiblaRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TasbeehRoute: typeof TasbeehRoute
  AzkarCategoryRoute: typeof AzkarCategoryRoute
  AzkarIndexRoute: typeof AzkarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasbeeh': {
      id: '/tasbeeh'
      path: '/tasbeeh'
      fullPath: '/tasbeeh'
      preLoaderRoute: typeof TasbeehRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar/': {
      id: '/azkar/'
      path: '/azkar'
      fullPath: '/azkar/'
      preLoaderRoute: typeof AzkarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azkar/$category': {
      id: '/azkar/$category'
      path: '/azkar/$category'
      fullPath: '/azkar/$category'
      preLoaderRoute: typeof AzkarCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  QiblaRoute: QiblaRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TasbeehRoute: TasbeehRoute,
  AzkarCategoryRoute: AzkarCategoryRoute,
  AzkarIndexRoute: AzkarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
